### ISSUE TITLE
WIFD token information - next update of approved pull requests

### ISSUE THREAD

**Issue by dogwifdots** [subscan-explorer/assets-info#52]
Dear subscan team,

Any details on when the next update is being performed? Is it possible to perform an ad-hoc update?

Would love to see the WIFD token details and logo displayed on subscan :-)

Thanks in advance!

-> Pull request #50
-> Token symbol: WIFD
-> Token ID (asset hub): 17
-> HydraDx token ID: 1000082

Woof,
Dog wif dots dev

**Comment by carlhong** [comment]
<img width="1386" alt="image" src="https://github.com/subscan-explorer/assets-info/assets/11582958/5bfd4b3b-4ae3-498f-9b45-f2d963769425">
It is already updated.
