### ISSUE TITLE
Multisig owner

### ISSUE THREAD

**Issue by MoMannn** [subscan-explorer/assets-info#63]
I would like to add a new asset to the repo but am unable to generate the required signature since the asset owner is a multisig account from which it is not possible to generate a signature. 

How can I solve this issue?

**Comment by carlhong** [comment]
In this case, you can sign with a member of multisig account, we'll check manually for you.

**Comment by MoMannn** [comment]
Opened PR https://github.com/subscan-explorer/assets-info/pull/64
