### ISSUE TITLE
Display Token Contract Address for foreign assets.

### ISSUE THREAD

**Issue by alistair-singh** [subscan-explorer/assets-info#65]
Hi, 

Thanks for adding in erc20 metadata for foreign assets the below issue:
https://github.com/subscan-explorer/assets-info/issues/62

Users cannot easily verify that the assets on the following pages are trusted as anyone can register an asset on Ethereum with any ERC20 metadata.
https://assethub-polkadot.subscan.io/foreign_assets/f1846f14a52715c2a09df52ef8f077c52977dcfd
https://assethub-polkadot.subscan.io/assets?tab=foreign-assets

Users cannot see the underlying token address so that they can verify the token themselves. 

We require:
1. The token contract address to be displayed in the subscan UI.
2. A link to Etherscan so that users can easily verify, but is not critical, just a UX improvement.

**Comment by carlhong** [comment]
<img width="552" alt="image" src="https://github.com/user-attachments/assets/f0917335-3483-4d77-a835-52af2c6011f2">
You can see location detail if you hover over "FOREIGN ASSET" label.
