### ISSUE TITLE
Add Million (Mill)

### ISSUE THREAD

**Issue by caybach** [subscan-explorer/assets-info#85]
Ticker
Mill

Asset Hub ID
22222070

Hydration ID
1000453

Icon SVG or PNG < 30kb 128x128
![1 M copy](https://github.com/user-attachments/assets/5fb8f49e-8a91-4ed9-ae9d-01b98dc1b769)

**Comment by WRRicht3r** [comment]
Hi, pls follow the instructions [here](https://github.com/subscan-explorer/assets-info?tab=readme-ov-file#how-to-update) to add a new asset!
